### PR TITLE
Captain gloves insulated.

### PR DESCRIPTION
**Pull request by IMVader**
Added just two lines into captain gloves code, give them the yellow gloves properties.

### CODE REVIEW

**Comment by IMVader** [comment]
http://llagaming.net/forums/threads/insulated-captains-gloves.3623/

**Comment by Setheri** [comment]
Why did you change the permeability coefficient exactly? That controls how chemicals/diseases affect the wearer and as far as I know wasn't discussed in the thread?

**Comment by FlavoredCactus** [comment]
Remove permeability coefficient

**Comment by IMVader** [comment]
The permeability coefficient was present both in the insulated and combat gloves. Removed now.

**Comment by FlavoredCactus** [comment]
Test this please.

**Comment by IMVader** [comment]
Tested. Works.

**Pull request merged**
