### PR TITLE
Fix ninja objectives

### PR DESCRIPTION
**Pull request by Ahbahl**
Removes RP objective
Changes objective/steal/special to objective/steal

Thread: http://www.llagaming.net/forums/threads/ninja-v3-fix-objectives.4240/

Also adds the RP fluff to the memory as Cactus suggested.

### CODE REVIEW

**Comment by Ahbahl** [comment]
Does it need testing though? http://i.gyazo.com/4b30f584c3dd7f3c6982c4b952db5540.png

**Comment by FlavoredCactus** [comment]
doesn't he need like 2 more objectives?

**Comment by Ahbahl** [comment]
Cant get assasinate/debrain/capture etc when I am the only one my test server.

**Comment by FlavoredCactus** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by FlavoredCactus** [comment]
Was told this could be merged in.

**Pull request merged**
