### PR TITLE
Update admins.txt

### PR DESCRIPTION
**Pull request by Setheri**
Updates admins.txt to make coding slightly less troublesome for me and flavo to test
Does not affect the server itself, only test servers.

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
this will effect the server on the next patch but drache/spoffy/taicho just needs to fix it as soon as it patchs.

**Comment by Setheri** [comment]
It shouldn't affect the server *at all* because the server reads admin ranks from the database, not admins.txt

**Comment by FlavoredCactus** [comment]
I am fairly certain we use the legacy system.. not the DB.

**Comment by xXTheDracheXx** [comment]
We don't use the DB for admins, also, it would get updated on the next patch.

**Comment by xXTheDracheXx** [comment]
I think I'm just going to close this.

**Comment by FlavoredCactus** [comment]
h8

**Pull request closed without merging**
