### PR TITLE
Fixed the water mister bug

### PR DESCRIPTION
**Pull request by QuantumWings**
See https://github.com/Spoffy/LLA-Station-13/issues/68

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
I can still put nozzles in lockers but it doesn't duplicate them.

**Comment by LLADonZombie** [comment]
I dont know about this bug, does this resolve it flavo?
is this server ready?

**Comment by FlavoredCactus** [comment]
I don't think so id like to hear back from QW

**Comment by LLADonZombie** [comment]
Cool. PM me with an update on this when you find out.

**Comment by QuantumWings** [comment]
This bug allows the mister to be in two places at once. It seems to be a nasty sort of bug that comes and goes almost randomly. I have on the same revision been able to replicate the bug, and then later be unable to trigger it. This patch prevents it from being placed in lockers or on tables.
A second opinion from someone who knows a bit more about debugging BYOND would be welcome just to make sure it doesn't do bad things when move(dest) fails.

**Comment by FlavoredCactus** [comment]
i still was able to place it in a locker though.

**Comment by QuantumWings** [comment]
Damn it! Atmos ones are different and doesn't inherit the way the janitor's one does.
Fixed it now.

**Comment by FlavoredCactus** [comment]
Do a test on all 3 and if you could, please add the w_class from the janitor one to the atmos one so it cant be bagged.

**Comment by QuantumWings** [comment]
I have tested all 3 with the bag and on tables and lockers.
Unfortunately have found other forms of the bug with disposals, conveyor belts and bags of holding.
To fix them changes would be needed to made with them to use item.Move(new_loc) rather than item.loc = new_loc

**Comment by LLADonZombie** [comment]
i hope this was done

**Pull request merged**
