### PR TITLE
Ai core

### PR DESCRIPTION
**Pull request by Daddysds1**
Because the other one was shit.

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
Please resolve the merge conflict.

**Comment by FlavoredCactus** [comment]
Seems you are using a really old version of the map that isn't up to date to merge this (you are still on the main branch), the version of the map you should be using is https://github.com/Spoffy/LLA-Station-13/blob/master/_maps/map_files/tgstation.2.1.3.dmm additionally if you could use the mapmerger tool for this as well that would be swell

**Comment by Daddysds1** [comment]
BAH i hate github i hate ittttt.

**Comment by FlavoredCactus** [comment]
Closed on request of the OP

**Pull request closed without merging**
