### PR TITLE
Some ninja changes

### PR DESCRIPTION
**Pull request by Ahbahl**
Reduced energy blade damage to 45.
EMP, ninjastar and drawing an energy blade uncloak.
Drops energy blades when enabling stealth.
Changed special steal objective to the normal steal objective because it
caused the "Nothing" objective.
Removed RP objective.
Removed energy net. (Commented out)
Changed "Slay alien queen" objective to "Protect alien queen" if working
for the syndicate.
Removed "capture" objective. (Commented out)
Alternated survive objective with an escape objective if working for NT.
9 tile teleport gibs anyone unfortunate to be there and the ninja.
Rightclick teleport stuns for the same duration as a flash.

turf.dm edited to add the new procs for the teleports.
Also energy net verbs commented out.

http://www.llagaming.net/forums/threads/ninja-v1.3890/ <- Feedback
http://www.llagaming.net/forums/threads/space-ninjas.3288/ <- Suggestion

### CODE REVIEW

**Comment by dbaininaz** [comment]
Why would the ninja be gibbed by his own ability?
Why would the syndicate protect xenos?
Why was it necessary to remove the capture net?

**Comment by dbaininaz** [comment]
Do you listen to anyone when you decide you want to code something, or just those who agree with you?

**Comment by Ahbahl** [comment]
The 8-9 tile ability gibs the ninja too because its inaccurate so materializing inside of someones body is certainly possible and would definitely result in the death of both parties.
Syndicate would protect xeno because xeno are on NT station so xenos that are alive destroy the station which is good for the syndicate, also possibility of xenos going on escape shuttle and infesting CentComm. Before it was kill xeno when you work for the syndicate which didnt make any sense either.
Not necessary, but it was griefy. Almost the same as admin prison, just a little bigger. And its not completely removed, its commented out (read: code is there but inactive) until someone fixes that issue,.
And yes, I do listen to everyone:
http://strawpoll.me/4014839
http://strawpoll.me/4014863
http://strawpoll.me/4014911
^- these are in the feedback thread

**Comment by dbaininaz** [comment]
How doesn't the xeno situation make sense? They are a predominantly evil force in the universe. A hive full of xenomorphs is more of a threat to any syndicate than any research station.

**Comment by dbaininaz** [comment]
Additionally, murder boning is griefy. Keeping players alive, albeit in a controlled area, is not.

Adding their antagonist status to this, and all you're doing is removing their most unique feature.

**Comment by xXTheDracheXx** [comment]
I don't get the ninja hate so I do not support.

**Comment by dbaininaz** [comment]
I've killed plenty of ninjas as a regular crew member, myself. Once their battery is out they have a disadvantage.

**Comment by LLADonZombie** [comment]
Drache insists this PR is pointless, and the polls seem inconclusive with approximately 50% support (including my own). It's just too widely divided and I can't find conclusive data that these changes are actually something people want.

**Pull request closed without merging**
