### PR TITLE
Mineral solidification changes

### PR DESCRIPTION
**Pull request by cody522**
Allows uranium, gold, and silver to go from liquid to solids. 
Replaced frost oil with clonexadone. Nobody got time to mutate all the species needed to get these chemicals.

Added silver to moonflowers from hydroponics. The three minerals can be harvested from botany.

### CODE REVIEW

**Comment by cody522** [comment]
i don't know what I'm doing

**Comment by Setheri** [comment]
/datum/chemical_reaction/uranusiamsolidification

*glare*

**Comment by FlavoredCactus** [comment]
please fix that cody

**Comment by cody522** [comment]
Github had some weird junk added to the file. But it's all fixed now.
Uranusiam was good by the way.

**Comment by LLADonZombie** [comment]
Since we don't have a feedback thread for this one, can you guys make an extra special pass to verify the quality of the PR postedit.

**Comment by Setheri** [comment]
Looks kosher to me, Zombie.

**Comment by FlavoredCactus** [comment]
Its k, wish he squashed his commits but i aint trippin.

**Comment by xXTheDracheXx** [comment]
The commit names aren't very great, and I'd really appreciate a squash. Seeing as we don't have the guidelines in place at this moment, this shouldn't be an issue right now.

**Comment by Setheri** [comment]
Cody, remind me or Flavo to teach you how to squash commits at a later time. (Or wait for drache to make a guide). Basically Squashing turns several commits into a single commit, which makes things cleaner when you did things like went back and corrected several errors or bugs.

**Pull request merged**
