### PR TITLE
Healing Sting

### PR DESCRIPTION
**Pull request by Ahbahl**
Adds a healing sting which heals the target over time.

http://www.llagaming.net/forums/threads/changeling-healing-sting.3697/ <- Suggestion thread
http://www.llagaming.net/forums/threads/healing-sting.3931/ <- Feedback thread

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
Can you revert the changelog edit, we do those before a server update and this would cause a conflict of some sort.

**Comment by Ahbahl** [comment]
Like this?

**Comment by Ahbahl** [comment]
That should do it.

**Comment by FlavoredCactus** [comment]
Looks fine, squash your commits if you know how to do it.

**Comment by Ahbahl** [comment]
No, I dont know how to do that. How do I do it?

**Comment by FlavoredCactus** [comment]
Which git program you using?

**Comment by Ahbahl** [comment]
GitHub for Windows. The one from the first guide.

**Comment by FlavoredCactus** [comment]
right click the fork in github for windows, click gitshell

git rebase Healing-Sting -i HEAD~4

a text file will open up looking like
pick changelog.html
pick healing sting
pick updates tiny prick
pick changelog.html

keep one as pick, the one you want to be the commit message then change the rest to squash. save the text file and close it out

**Comment by Ahbahl** [comment]
I get this. 
# Rebase a22bdf4..0e279f3 onto a22bdf4
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

**Comment by Ahbahl** [comment]
I get this 
http://pastebin.com/gTR41mBH

**Comment by FlavoredCactus** [comment]
Anything above that?

**Comment by Ahbahl** [comment]
Yes, "noop" without the "s. No # either

**Comment by FlavoredCactus** [comment]
try git rebase -i HEAD~4

**Comment by Ahbahl** [comment]
Yes, that works.

**Comment by Ahbahl** [comment]
Gah, it doesnt work like I want it to work

**Comment by FlavoredCactus** [comment]
close this one, make a new branch off your master, put all your changes into it and make 1 commit then make a new PR

**Comment by Ahbahl** [comment]
Aye

**Pull request closed without merging**
